Repository pokealarm/pokealarm, pull requests merged in 2018-04, with the labels that each got.

#656 Logging Rework
  .gitignore
  PokeAlarm/Alarms/Discord/DiscordAlarm.py
  PokeAlarm/Alarms/FacebookPage/FacebookPageAlarm.py
  PokeAlarm/Alarms/Pushbullet/PushBulletAlarm.py
  PokeAlarm/Alarms/Slack/SlackAlarm.py
  PokeAlarm/Alarms/Telegram/TelegramAlarm.py
  PokeAlarm/Alarms/Twilio/TwilioAlarm.py
  PokeAlarm/Alarms/Twitter/TwitterAlarm.py
  PokeAlarm/Alarms/__init__.py
  PokeAlarm/Cache/Cache.py
  PokeAlarm/Cache/FileCache.py
  PokeAlarm/Cache/__init__.py
  PokeAlarm/Filters/BaseFilter.py
  PokeAlarm/Filters/EggFilter.py
  PokeAlarm/Filters/GymFilter.py
  PokeAlarm/Filters/MonFilter.py
  PokeAlarm/Filters/RaidFilter.py
  PokeAlarm/Filters/StopFilter.py
  PokeAlarm/Load.py
  PokeAlarm/Manager.py
  PokeAlarm/Utilities/Logging.py
  PokeAlarm/Utils.py
  config/config.ini.example
  start_pokealarm.py
  tests/filters/__init__.py
  tests/filters/test_egg_filter.py
  tests/filters/test_gym_filter.py
  tests/filters/test_monster_filter.py
  tests/filters/test_raid_filter.py
  tests/filters/test_stop_filter.py
Labels: enhancement, new feature

#658 Setting up Waze Deep Linking
  .gitignore
  PokeAlarm/Events/EggEvent.py
  PokeAlarm/Events/GymEvent.py
  PokeAlarm/Events/MonEvent.py
  PokeAlarm/Events/RaidEvent.py
  PokeAlarm/Events/StopEvent.py
  PokeAlarm/Utils.py
  docs/configuration/events/egg-events.rst
  docs/configuration/events/gym-events.rst
  docs/configuration/events/monster-events.rst
  docs/configuration/events/raid-events.rst
  docs/configuration/events/stop-events.rst
Labels: new feature

#657 Weather Webhooks!
  PokeAlarm/Alarms/Alarm.py
  PokeAlarm/Alarms/Discord/DiscordAlarm.py
  PokeAlarm/Alarms/FacebookPage/FacebookPageAlarm.py
  PokeAlarm/Alarms/Pushbullet/PushBulletAlarm.py
  PokeAlarm/Alarms/Slack/SlackAlarm.py
  PokeAlarm/Alarms/Telegram/TelegramAlarm.py
  PokeAlarm/Alarms/Twilio/TwilioAlarm.py
  PokeAlarm/Alarms/Twitter/TwitterAlarm.py
  PokeAlarm/Cache/Cache.py
  PokeAlarm/Cache/FileCache.py
  PokeAlarm/Events/WeatherEvent.py
  PokeAlarm/Events/__init__.py
  PokeAlarm/Filters/WeatherFilter.py
  PokeAlarm/Filters/__init__.py
  PokeAlarm/Load.py
  PokeAlarm/Locale.py
  PokeAlarm/Manager.py
  PokeAlarm/Utilities/WeatherUtils.py
  docs/configuration/events/weather-events.rst
  docs/configuration/filters/index.rst
  docs/configuration/filters/weather-filters.rst
  docs/configuration/rules.rst
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/it.json
  locales/ko.json
  locales/pt.json
  locales/zh_hk.json
  tests/filters/test_weather_filter.py
  tools/webhook_test.py
Labels: in progress, new feature
