Repository pokealarm/pokealarm, pull requests merged in 2018-02, with the labels that each got.

#610 Move Types
  PokeAlarm/Events/MonEvent.py
  PokeAlarm/Events/RaidEvent.py
  PokeAlarm/Filters/MonFilter.py
  PokeAlarm/Filters/RaidFilter.py
  PokeAlarm/Utils.py
  data/move_info.json
Labels: needs wiki update, new feature

#611 Adds gym_name_excludes filter to Gym, Egg, Raid Events
  PokeAlarm/Filters/EggFilter.py
  PokeAlarm/Filters/GymFilter.py
  PokeAlarm/Filters/RaidFilter.py
  PokeAlarm/Utilities/GymUtils.py
  tests/filters/test_egg_filter.py
  tests/filters/test_gym_filter.py
  tests/filters/test_raid_filter.py
Labels: needs wiki update, new feature

#613 Adds Costume Support to MonEvent & RaidEvent
  PokeAlarm/Events/MonEvent.py
  PokeAlarm/Events/RaidEvent.py
  PokeAlarm/Filters/MonFilter.py
  PokeAlarm/Locale.py
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/it.json
  locales/ko.json
  locales/pt.json
  tests/filters/test_monster_filter.py
Labels: needs wiki update, new feature

#603 Add restrictions and DTS for Gym Sponsor and Parks.
  PokeAlarm/Events/EggEvent.py
  PokeAlarm/Events/RaidEvent.py
  PokeAlarm/Filters/EggFilter.py
  PokeAlarm/Filters/RaidFilter.py
  tests/filters/test_egg_filter.py
  tests/filters/test_raid_filter.py
Labels: needs wiki update, new feature

#612 GMaps Improvements
  PokeAlarm/LocationServices/GMaps.py
  PokeAlarm/LocationServices/GoogleMaps.py
  PokeAlarm/LocationServices/__init__.py
  PokeAlarm/Manager.py
  PokeAlarm/Utilities/GenUtils.py
  config/config.ini.example
  requirements.txt
  start_pokealarm.py
Labels: bug fix, needs wiki update, new feature

#620 Telegram Web Preview Option
  PokeAlarm/Alarms/Telegram/TelegramAlarm.py
Labels: needs wiki update, new feature

#621 Fixed is_sponsor filter for Raids
  PokeAlarm/Filters/RaidFilter.py
Labels: bug fix

#615 Adding catch prob and rating attack-defense DTS
  PokeAlarm/Events/MonEvent.py
  docs/dts/monster-dts.md
Labels: changes requested, new feature
