Repository pokealarm/pokealarm, pull requests merged in 2019-12, with the labels that each got.

#705 Add grunt_hist to cache cleaning and file cache
  PokeAlarm/Cache/Cache.py
  PokeAlarm/Cache/FileCache.py
Labels: Priority: Medium, Status: Proposal, Type: Bug

#694 New shadow forms & Normal forms
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/it.json
  locales/ko.json
  locales/pt.json
  locales/zh_hk.json
Labels: Priority: Low, Status: Available, Type: Bug

#700 Base Stats Update
  data/base_stats.json
  locales/en.json
Labels: Priority: Low, Status: In Progress, Type: Maintenance
