Repository pokealarm/pokealarm, pull requests merged in 2020-03, with the labels that each got.

#708 Custom Static Map Alarm Field
  PokeAlarm/Alarms/Discord/DiscordAlarm.py
  PokeAlarm/Alarms/Slack/SlackAlarm.py
  docs/configuration/alarms/discord.rst
  docs/configuration/alarms/slack.rst
Labels: Priority: Low, Status: In Progress, Type: Feature Request

#706 MAD Quests
  PokeAlarm/Alarms/Discord/DiscordAlarm.py
  PokeAlarm/Alarms/FacebookPage/FacebookPageAlarm.py
  PokeAlarm/Alarms/Pushbullet/PushBulletAlarm.py
  PokeAlarm/Alarms/Slack/SlackAlarm.py
  PokeAlarm/Alarms/Telegram/TelegramAlarm.py
  PokeAlarm/Alarms/Twilio/TwilioAlarm.py
  PokeAlarm/Alarms/Twitter/TwitterAlarm.py
  PokeAlarm/Cache/Cache.py
  PokeAlarm/Events/QuestEvent.py
  PokeAlarm/Filters/QuestFilter.py
  PokeAlarm/Load.py
  PokeAlarm/Locale.py
  PokeAlarm/Manager.py
  PokeAlarm/Utilities/QuestUtils.py
  docs/configuration/alarms/discord.rst
  docs/configuration/alarms/facebook-pages.rst
  docs/configuration/alarms/slack.rst
  docs/configuration/alarms/telegram.rst
  docs/configuration/events/index.rst
  docs/configuration/events/quest-events.rst
  docs/configuration/filters/index.rst
  docs/configuration/filters/quest-filters.rst
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/it.json
  locales/ko.json
  locales/pt.json
  locales/zh_hk.json
  tests/filters/test_quest_filter.py
  tools/webhook_test.py
Labels: Priority: High, Status: In Progress, Type: Feature Request

#693 Fixed weather/severity event issues
  PokeAlarm/Events/WeatherEvent.py
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/it.json
  locales/ko.json
  locales/pt.json
  locales/zh_hk.json
Labels: Priority: High, Status: In Progress, Type: Bug
