Repository pokealarm/pokealarm, pull requests merged in 2020-01, with the labels that each got.

#695 Translation fixes
  locales/de.json
Labels: Type: Maintenance

#709 Version bump everything
  docs/configuration/events/invasion-events.rst
  requirements.txt
Labels: Type: Maintenance

#710 Spawn Verified DTS
  PokeAlarm/Events/MonEvent.py
  PokeAlarm/Utils.py
  docs/configuration/events/monster-events.rst
Labels: Priority: Low, Status: In Progress, Status: Test Needed

#699 Add stuff for forms/costumes
  PokeAlarm/Events/MonEvent.py
  PokeAlarm/Events/RaidEvent.py
  PokeAlarm/Filters/MonFilter.py
  PokeAlarm/Filters/RaidFilter.py
  docs/configuration/events/monster-events.rst
  docs/configuration/events/raid-events.rst
  docs/configuration/filters/monster-filters.rst
  docs/configuration/filters/raid-filters.rst
  tests/filters/test_monster_filter.py
  tests/filters/test_raid_filter.py
Labels: Type: Feature Request
