Repository pokealarm/pokealarm, pull requests merged in 2023-01, with the labels that each got.

#855 JSON5 support
  .gitignore
  PokeAlarm/Load.py
  requirements.txt
Labels: type: feature, hacktoberfest-accepted

#854 GitPod Configuration
  .gitignore
  .gitpod.yml
  .vscode/launch.json
Labels: type: feature, hacktoberfest-accepted

#857 Docs Fixes: Typos, grammar, link fixes, link adds, etc
  docs/configuration/events/monster-events.rst
  docs/configuration/events/quest-events.rst
  docs/configuration/events/raid-events.rst
  docs/configuration/filters/egg-filters.rst
  docs/configuration/filters/gym-filters.rst
  docs/configuration/filters/invasion-filters.rst
  docs/configuration/filters/monster-filters.rst
  docs/configuration/filters/raid-filters.rst
Labels: type: docs, hacktoberfest-accepted

#866 New checks for missing monster data
  PokeAlarm/Alarms/Discord/DiscordAlarm.py
  PokeAlarm/Utils.py
  tools/webhook_test.py
Labels: priority: critical, type: bug

#865 Pvp info speedup
  PokeAlarm/Events/MonEvent.py
  PokeAlarm/Events/RaidEvent.py
  PokeAlarm/Utilities/PvpUtils.py
  PokeAlarm/Utils.py
  data/powerup_costs.json
  tests/test_get_pvp_info.py
  tools/pvp.py
Labels: type: feature
